### ISSUE TITLE
buildout fails on version 0.14.0

### ISSUE THREAD

**Issue by DavidPesta** [mgedmin/zodbbrowser#28] opened 2018-04-27 01:15 UTC
Ubuntu 16.04
$ python3.6 bootstrap.py
$ bin/buildout

```
...
Got zope.pluggableauth 2.3.0.
Getting distribution for 'zope.container'.
Got zope.container 4.2.1.
Getting distribution for 'traceback2'.
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)

Installed /tmp/easy_install-jaoq5aq_/traceback2-1.4.0/.eggs/pbr-4.0.2-py3.6.egg
Got traceback2 1.4.0.
Getting distribution for 'argparse'.
/usr/lib/python3/dist-packages/setuptools/extern/__init__.py:1: UserWarning: Module argparse was already imported from /usr/lib/python3.6/argparse.py, but /tmp/easy_install-gqdxewa0/argparse-1.4.0 is being added to sys.path
  from pkg_resources.extern import VendorImporter
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.orig' found anywhere in distribution
warning: no previously-included files matching '*.rej' found anywhere in distribution
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'env24'
no previously-included directories found matching 'env25'
no previously-included directories found matching 'env26'
no previously-included directories found matching 'env27'
zip_safe flag not set; analyzing archive contents...
While:
  Installing python.
  Getting distribution for 'argparse'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 2127, in main
    getattr(buildout, command)(args)
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 797, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 1557, in _call
    return f()
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 221, in install
    reqs, ws = self.working_set()
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts,
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 162, in _working_set
    allow_hosts=allow_hosts)
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/easy_install.py", line 924, in install
    return installer.install(specs, working_set)
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/easy_install.py", line 726, in install
    for dist in self._get_dist(req, ws):
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/easy_install.py", line 570, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/david/zodbbrowser/zodbbrowser-0.14.0/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/easy_install.py", line 1735, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError
```

**Comment by mgedmin** [comment] 2018-04-27 09:57
This looks like a zc.buildout bug to me.

On the other hand, why try to install `argparse` on Python 3.6, when `argparse` is part of the standard library since 2.7?  Maybe you can discover whichever package depends on argparse and ask the maintainer to fix that? 

Meanwhile I suggest using virtualenv + pip to install zodbbrowser, until this mess is resolved.

**Comment by mgedmin** [comment] 2018-04-27 10:04
For the record I cannot reproduce on Ubuntu 17.10, if I run buildout in a virtualenv:

```
virtualenv -p python3.6 .venv
.venv/bin/python bootstrap.py
bin/buildout
```

**Comment by mgedmin** [comment] 2018-04-27 10:05
I'm closing this because it's a zc.buildout bug with existing workarounds.

**Closed by mgedmin** 2018-04-27 10:04 UTC

**Comment by DavidPesta** [comment] 2018-04-27 10:09
virtualenv + pip is a great idea! I'll try that later today. Thanks!
